using Descrio.Generator.Callable.Models;
using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Descrio.Generator.Callable
{
    /// <summary>
    /// Responsible for generating the source code for [Callable] method wrappers and the
    /// AddCallables extension methods.
    /// </summary>
    internal static class CodeBuilder
    {
        public static string BuildWrapperClass(CallableClassInfo classInfo, CallableMethodInfo methodInfo)
        {
            var sb = new IndentedStringBuilder();
            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();

            var hasNamespace = !string.IsNullOrEmpty(classInfo.Namespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                sb.AppendLine("{");
                sb.IncreaseIndent();
            }

            sb.AppendLine($"// Auto-generated wrapper for {classInfo.FullClassName}.{methodInfo.MethodName}");
            sb.AppendLine($"internal class {wrapperClassName} : Descrio.ICallable");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"private readonly {classInfo.FullClassName} _target;");
                sb.AppendLine($"public {wrapperClassName}({classInfo.FullClassName} target) => _target = target;");
                sb.AppendLine();

                var asyncKeyword = methodInfo.IsAwaitable ? "async " : "";
                sb.AppendLine($"public {asyncKeyword}System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)");
                using (sb.IndentedBlock())
                {
                    var callParams = AppendParametersLogic(sb, methodInfo.Parameters);
                    AppendMethodCallLogic(sb, methodInfo, callParams);
                }
            }

            if (hasNamespace)
            {
                sb.DecreaseIndent();
                sb.AppendLine("}");
            }
            sb.AppendLine("#nullable disable");

            return sb.ToString();
        }

        private static List<string> AppendParametersLogic(IndentedStringBuilder sb, List<ParameterInfo> parameters)
        {
            var callParamNames = new List<string>();
            foreach (var param in parameters)
            {
                var typeName = param.TypeName;
                if (typeName == "global::System.Threading.CancellationToken")
                {
                    callParamNames.Add("context.CancellationToken");
                    continue;
                }
                if (typeName == "global::Descrio.Execution.ExecutionContext")
                {
                    callParamNames.Add("context");
                    continue;
                }

                var paramName = param.Name;

                sb.AppendLine($"object? p_val_{paramName};");
                if (param.HasDefaultValue)
                {
                    sb.AppendLine($"p_val_{paramName} = args.TryGetValue(\"{paramName}\", out var val_{paramName}) ? val_{paramName} : {param.DefaultValueAsString};");
                }
                else
                {
                    sb.AppendLine($"if (!args.TryGetValue(\"{paramName}\", out p_val_{paramName})) throw new System.ArgumentException(\"Missing required argument: '{paramName}'.\");");
                }

                sb.AppendLine($"var p_targetType_{paramName} = typeof({typeName});");
                sb.AppendLine($"if (p_val_{paramName} != null && !p_targetType_{paramName}.IsInstanceOfType(p_val_{paramName}))");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("if (Descrio.Execution.Converters.TypeConverterRegistry.TryGetConverter(p_targetType_{paramName}, out var converter))");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"p_val_{paramName} = converter.Convert(p_val_{paramName});");
                    }
                    sb.AppendLine("else");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"p_val_{paramName} = System.Convert.ChangeType(p_val_{paramName}, p_targetType_{paramName});");
                    }
                }

                sb.AppendLine($"var p_{paramName} = ({typeName}?)p_val_{paramName};");

                callParamNames.Add($"p_{paramName}");
                sb.AppendLine();
            }
            return callParamNames;
        }

        private static void AppendMethodCallLogic(IndentedStringBuilder sb, CallableMethodInfo methodInfo, List<string> callParamNames)
        {
            var callParamsStr = string.Join(", ", callParamNames);

            if (methodInfo.IsAwaitable)
            {
                if (methodInfo.ReturnsValue)
                {
                    sb.AppendLine($"var result = await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return (object?)result;");
                }
                else
                {
                    sb.AppendLine($"await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return null;");
                }
            }
            else
            {
                if (methodInfo.ReturnsValue)
                {
                    sb.AppendLine($"var result = _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return new ValueTask<object?>(result);");
                }
                else
                {
                    sb.AppendLine($"_target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return new ValueTask<object?>(null);");
                }
            }
        }

        public static string BuildRegistrationClass(string accessibility, string className, IEnumerable<CallableClassInfo> classInfos)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Descrio;");
            sb.AppendLine();
            sb.AppendLine($"{accessibility} static class {className}");
            using (sb.IndentedBlock())
            {
                foreach (var classInfo in classInfos)
                {
                    sb.AppendLine($"public static ScriptRunner AddCallables(this ScriptRunner runner, {classInfo.FullClassName} target)");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine("if (target == null) return runner;");

                        foreach (var methodInfo in classInfo.Methods)
                        {
                            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";
                            var fullWrapperName = string.IsNullOrEmpty(classInfo.Namespace) ? wrapperClassName : $"{classInfo.Namespace}.{wrapperClassName}";
                            sb.AppendLine($"runner.AddCallable(\"{methodInfo.CallableName}\", new {fullWrapperName}(target));");
                        }

                        sb.AppendLine("return runner;");
                    }
                    sb.AppendLine();
                }
            }
            return sb.ToString();
        }
    }
}