using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Descrio.Generator.Callable
{
    /// <summary>
    /// Responsible for generating the source code for ITypeConverter implementations.
    /// </summary>
    internal static class ConverterBuilder
    {
        /// <summary>
        /// Builds the source code for a single TypeConverter class that handles mapping a dictionary to a specific class type.
        /// </summary>
        /// <param name="typeSymbol">The symbol of the class/struct to create a converter for.</param>
        /// <param name="allMappableTypes">A collection of all types that will have converters, used to handle nested types correctly.</param>
        /// <returns>The generated C# source code for the converter class.</returns>
        public static string BuildTypeConverterClass(ITypeSymbol typeSymbol, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_");
            var converterClassName = $"__Descrio_{safeClassName}_Converter";

            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Descrio.Execution.Converters;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            var ns = typeSymbol.ContainingNamespace;
            var hasNamespace = ns != null && !ns.IsGlobalNamespace;

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns.ToDisplayString()}");
                sb.AppendLine("{");
                sb.IncreaseIndent();
            }

            sb.AppendLine($"internal class {converterClassName} : ITypeConverter");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"public object? Convert(object? source)");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("if (source == null) return null;");
                    sb.AppendLine("if (!(source is IDictionary<object, object> dataDict))");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"throw new InvalidCastException($\"Expected a dictionary to map to {fullTypeName}, but received a {{source.GetType().Name}}.\");");
                    }
                    sb.AppendLine();
                    sb.AppendLine($"var instance = new {fullTypeName}();");

                    foreach (var member in typeSymbol.GetMembers().OfType<ISymbol>().Where(m => m is IPropertySymbol || m is IFieldSymbol))
                    {
                        (string? memberName, ITypeSymbol? memberType, bool canWrite) = GetMemberInfo(member);
                        if (!canWrite || memberName is null || memberType is null)
                            continue;

                        var memberTypeName = memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        sb.AppendLine($"if (dataDict.TryGetValue(\"{memberName}\", out var memberVal_{memberName}) && memberVal_{memberName} != null)");
                        using (sb.IndentedBlock())
                        {
                            sb.AppendLine("try");
                            using (sb.IndentedBlock())
                            {
                                AppendMemberConversionLogic(sb, "instance", memberName, memberType, memberTypeName, allMappableTypes);
                            }
                            sb.AppendLine("catch (Exception ex)");
                            using (sb.IndentedBlock())
                            {
                                sb.AppendLine($"throw new InvalidOperationException(\"Failed to map member '{memberName}' of type '{memberTypeName}'. See inner exception for details.\", ex);");
                            }
                        }
                    }
                    sb.AppendLine("return instance;");
                }
            }

            if (hasNamespace)
            {
                sb.DecreaseIndent();
                sb.AppendLine("}");
            }
            sb.AppendLine("#nullable disable");

            return sb.ToString();
        }

        public static (string?, ITypeSymbol?, bool) GetMemberInfo(ISymbol symbol)
        {
            if (symbol is IPropertySymbol prop && prop.SetMethod != null && prop.DeclaredAccessibility == Accessibility.Public)
            {
                return (prop.Name, prop.Type, true);
            }
            if (symbol is IFieldSymbol field && !field.IsReadOnly && field.DeclaredAccessibility == Accessibility.Public)
            {
                return (field.Name, field.Type, true);
            }
            return (null, null, false);
        }

        private static void AppendMemberConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol memberType, string memberTypeName, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var valueToConvert = $"memberVal_{memberName}";

            // Case 1: Nested Mappable Type
            if (allMappableTypes.Contains(memberType, SymbolEqualityComparer.Default))
            {
                sb.AppendLine($"if (TypeConverterRegistry.TryGetConverter(typeof({memberTypeName}), out var converter_{memberName}))");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName}?)converter_{memberName}.Convert({valueToConvert});");
                }
                sb.AppendLine("else");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"throw new InvalidOperationException($\"Converter not found for nested type '{memberTypeName}'. This should have been generated.\");");
                }
                return;
            }

            // Case 2: Enum Type
            if (memberType.BaseType != null && memberType.BaseType.ToDisplayString() == "global::System.Enum")
            {
                sb.AppendLine($"if ({valueToConvert} is string strVal_{memberName})");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName})Enum.Parse(typeof({memberTypeName}), strVal_{memberName}, true);");
                }
                sb.AppendLine("else");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName})Enum.ToObject(typeof({memberTypeName}), {valueToConvert});");
                }
                return;
            }

            // Case 3: Collection Types (List, Array)
            if (memberType is INamedTypeSymbol namedType && namedType.IsGenericType && namedType.ConstructedFrom.ToDisplayString() == "global::System.Collections.Generic.List<T>")
            {
                var itemType = namedType.TypeArguments[0];
                AppendCollectionConversionLogic(sb, instanceName, memberName, memberTypeName, itemType, valueToConvert, "ToList", allMappableTypes);
                return;
            }

            if (memberType is IArrayTypeSymbol arrayType)
            {
                var elementType = arrayType.ElementType;
                AppendCollectionConversionLogic(sb, instanceName, memberName, memberTypeName, elementType, valueToConvert, "ToArray", allMappableTypes);
                return;
            }

            // Case 4: Primitive or other convertible types
            sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName}?)System.Convert.ChangeType({valueToConvert}, typeof({memberTypeName}));");
        }

        private static void AppendCollectionConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, string memberTypeName, ITypeSymbol itemType, string valueToConvert, string linqMethod, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var itemTypeName = itemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"if ({valueToConvert} is not System.Collections.IEnumerable list_{memberName}) throw new InvalidCastException(\"Expected a list or array.\");");
            sb.AppendLine();
            sb.AppendLine($"{instanceName}.{memberName} = list_{memberName}.Cast<object>().Select(item =>");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("if (item == null) return null;");
                if (allMappableTypes.Contains(itemType, SymbolEqualityComparer.Default))
                {
                    sb.AppendLine($"if (!TypeConverterRegistry.TryGetConverter(typeof({itemTypeName}), out var converter)) throw new InvalidOperationException($\"Converter for list item '{itemTypeName}' not found.\");");
                    sb.AppendLine($"return ({itemTypeName}?)converter.Convert(item);");
                }
                else
                {
                    sb.AppendLine($"return ({itemTypeName}?)System.Convert.ChangeType(item, typeof({itemTypeName}));");
                }
            }
            sb.AppendLine($").{linqMethod}<{itemTypeName}?>();");
        }

        /// <summary>
        /// Builds the source code for the static initializer class that registers all generated converters.
        /// </summary>
        /// <param name="allMappableTypes">A collection of all types that have converters to be registered.</param>
        /// <returns>The generated C# source code for the initializer class.</returns>
        public static string BuildInitializerClass(IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Descrio.Execution.Converters;");
            sb.AppendLine();

            sb.AppendLine("namespace Descrio.Generated");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("/// <summary>");
                sb.AppendLine("/// Contains the entry point for initializing all source-generated components for Descrio.");
                sb.AppendLine("/// This is called automatically by the runtime and should not be called manually.");
                sb.AppendLine("/// </summary>");
                sb.AppendLine("internal static partial class DescrioInitializer");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("/// <summary>");
                    sb.AppendLine("/// Registers all auto-generated type converters with the Descrio runtime.");
                    sb.AppendLine("/// </summary>");
                    sb.AppendLine("internal static void Initialize()");
                    using (sb.IndentedBlock())
                    {
                        foreach (var typeSymbol in allMappableTypes)
                        {
                            var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_");
                            var converterClassName = $"__Descrio_{safeClassName}_Converter";

                            var ns = typeSymbol.ContainingNamespace;
                            var hasNamespace = ns != null && !ns.IsGlobalNamespace;
                            var fullConverterClassName = hasNamespace
                                ? $"{ns.ToDisplayString()}.{converterClassName}"
                                : converterClassName;

                            sb.AppendLine($"TypeConverterRegistry.RegisterCore(typeof({fullTypeName}), new {fullConverterClassName}());");
                        }
                    }
                }
            }

            // Also generate the partial class definition for the engine side to hook into.
            sb.AppendLine();
            sb.AppendLine("namespace Descrio.Execution.Converters");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("public static partial class TypeConverterRegistry");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("static partial void InitializeConverters()");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine("Descrio.Generated.DescrioInitializer.Initialize();");
                    }
                }
            }

            return sb.ToString();
        }
    }
}