//HintName: __Descrio_MyGame_Actions_GenericActions_ProcessGenericData_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.GenericActions.ProcessGenericData
    internal class __Descrio_MyGame_Actions_GenericActions_ProcessGenericData_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.GenericActions _target;
        public __Descrio_MyGame_Actions_GenericActions_ProcessGenericData_Callable(global::MyGame.Actions.GenericActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            p_val_data = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.GenericData<string>>(p_val_data);
            var p_data = (global::MyGame.Data.GenericData<string>?)p_val_data;
            
            _target.ProcessGenericData(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
