//HintName: __Descrio_MyGame_Actions_NullableActions_Process_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.NullableActions.Process
    internal class __Descrio_MyGame_Actions_NullableActions_Process_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.NullableActions _target;
        public __Descrio_MyGame_Actions_NullableActions_Process_Callable(global::MyGame.Actions.NullableActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_count;
            if (!args.TryGetValue("count", out p_val_count)) throw new System.ArgumentException("Missing required argument: 'count'.");
            p_val_count = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<int?>(p_val_count);
            var p_count = (int?)p_val_count;
            
            object? p_val_value;
            if (!args.TryGetValue("value", out p_val_value)) throw new System.ArgumentException("Missing required argument: 'value'.");
            p_val_value = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<float?>(p_val_value);
            var p_value = (float?)p_val_value;
            
            _target.Process(p_count, p_value);
            return default;
        }
    }
}
#nullable disable
