//HintName: __Descrio_MyGame_Data_SkillData_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_SkillData_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.SkillData, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.SkillData();
            if (dataDict.TryGetValue("SkillName", out var memberVal_SkillName) && memberVal_SkillName != null)
            {
                try
                {
                    instance.SkillName = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<string>(memberVal_SkillName);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'SkillName' of type 'string'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("Target", out var memberVal_Target) && memberVal_Target != null)
            {
                try
                {
                    instance.Target = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.TargetType>(memberVal_Target);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Target' of type 'global::MyGame.Data.TargetType'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("DamageEffects", out var memberVal_DamageEffects) && memberVal_DamageEffects != null)
            {
                try
                {
                    if (memberVal_DamageEffects is not System.Collections.IEnumerable list_DamageEffects) throw new InvalidCastException("Expected a list or array.");
                    
                    instance.DamageEffects = list_DamageEffects.Cast<object?>().Select(item =>
                    {
                        return global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.DamageInfo>(item);
                    }
                    ).ToList();
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'DamageEffects' of type 'global::System.Collections.Generic.List<global::MyGame.Data.DamageInfo>'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("BonusEffects", out var memberVal_BonusEffects) && memberVal_BonusEffects != null)
            {
                try
                {
                    if (memberVal_BonusEffects is not System.Collections.IEnumerable list_BonusEffects) throw new InvalidCastException("Expected a list or array.");
                    
                    instance.BonusEffects = list_BonusEffects.Cast<object?>().Select(item =>
                    {
                        return global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.DamageInfo>(item);
                    }
                    ).ToArray();
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'BonusEffects' of type 'global::MyGame.Data.DamageInfo[]'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
