//HintName: __DescrioPublicAddCallablesExtensions.g.cs
// <auto-generated/>
using Descrio;

public static class __DescrioPublicAddCallablesExtensions
{
    public static ScriptRunner AddCallables(this ScriptRunner runner, global::MyGame.Actions.DuplicateActions target)
    {
        if (target == null) return runner;
        runner.AddCallable("DoAction", new MyGame.Actions.__Descrio_MyGame_Actions_DuplicateActions_ActionOne_Callable(target));
        runner.AddCallable("DoAction", new MyGame.Actions.__Descrio_MyGame_Actions_DuplicateActions_ActionTwo_Callable(target));
        return runner;
    }
    
}
