//HintName: __DescrioGeneratedInitializers.g.cs
// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Descrio.Generated
{
    internal static class DescrioInitializer
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Data.SkillData), new global::MyGame.Data.__Descrio_MyGame_Data_SkillData_Converter());
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Data.DamageInfo), new global::MyGame.Data.__Descrio_MyGame_Data_DamageInfo_Converter());
        }
    }
}
