//HintName: __Descrio_MyGame_Data_EffectData_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_EffectData_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.EffectData, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.EffectData();
            if (dataDict.TryGetValue("Name", out var memberVal_Name) && memberVal_Name != null)
            {
                try
                {
                    instance.Name = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<string>(memberVal_Name);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Name' of type 'string'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("Power", out var memberVal_Power) && memberVal_Power != null)
            {
                try
                {
                    instance.Power = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<int>(memberVal_Power);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Power' of type 'int'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
