//HintName: __Descrio_MyGame_Data_CharacterStats_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_CharacterStats_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.CharacterStats, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.CharacterStats();
            if (dataDict.TryGetValue("Resistances", out var memberVal_Resistances) && memberVal_Resistances != null)
            {
                try
                {
                    if (memberVal_Resistances is not System.Collections.IDictionary dict_Resistances) throw new InvalidCastException($"Expected a dictionary for member 'Resistances'.");
                    
                    instance.Resistances = dict_Resistances
                        .Cast<System.Collections.DictionaryEntry>()
                        .ToDictionary(
                            entry => global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<string>(entry.Key) ?? throw new System.InvalidCastException("Dictionary key cannot be null."),
                            entry => global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<int>(entry.Value));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Resistances' of type 'global::System.Collections.Generic.Dictionary<string, int>'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("StatusEffects", out var memberVal_StatusEffects) && memberVal_StatusEffects != null)
            {
                try
                {
                    if (memberVal_StatusEffects is not System.Collections.IDictionary dict_StatusEffects) throw new InvalidCastException($"Expected a dictionary for member 'StatusEffects'.");
                    
                    instance.StatusEffects = dict_StatusEffects
                        .Cast<System.Collections.DictionaryEntry>()
                        .ToDictionary(
                            entry => global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<string>(entry.Key) ?? throw new System.InvalidCastException("Dictionary key cannot be null."),
                            entry => global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.EffectData>(entry.Value));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'StatusEffects' of type 'global::System.Collections.Generic.Dictionary<string, global::MyGame.Data.EffectData>'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
