//HintName: __Descrio_MyGame_Actions_StatusActions_ApplyStatus_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.StatusActions.ApplyStatus
    internal class __Descrio_MyGame_Actions_StatusActions_ApplyStatus_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.StatusActions _target;
        public __Descrio_MyGame_Actions_StatusActions_ApplyStatus_Callable(global::MyGame.Actions.StatusActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_stats;
            if (!args.TryGetValue("stats", out p_val_stats)) throw new System.ArgumentException("Missing required argument: 'stats'.");
            p_val_stats = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.CharacterStats>(p_val_stats);
            var p_stats = (global::MyGame.Data.CharacterStats?)p_val_stats;
            
            _target.ApplyStatus(p_stats);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
