//HintName: __DescrioGeneratedInitializers.g.cs
// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Descrio.Generated
{
    internal static class DescrioInitializer
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Data.GenericData<string>), new global::MyGame.Data.__Descrio_MyGame_Data_GenericData_string__Converter());
        }
    }
}
