//HintName: __Descrio_MyGame_Actions_MovementActions_MoveTo_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.MovementActions.MoveTo
    internal class __Descrio_MyGame_Actions_MovementActions_MoveTo_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.MovementActions _target;
        public __Descrio_MyGame_Actions_MovementActions_MoveTo_Callable(global::MyGame.Actions.MovementActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_position;
            if (!args.TryGetValue("position", out p_val_position)) throw new System.ArgumentException("Missing required argument: 'position'.");
            p_val_position = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.Vector2D>(p_val_position);
            if (p_val_position == null) throw new System.InvalidCastException($"Cannot convert null to non-nullable type global::MyGame.Data.Vector2D for parameter 'position'.");
            var p_position = (global::MyGame.Data.Vector2D)p_val_position!;
            
            _target.MoveTo(p_position);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
