//HintName: __Descrio_MyGame_Actions_SomeActions_HandleData_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.SomeActions.HandleData
    internal class __Descrio_MyGame_Actions_SomeActions_HandleData_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.SomeActions _target;
        public __Descrio_MyGame_Actions_SomeActions_HandleData_Callable(global::MyGame.Actions.SomeActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            p_val_data = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.DataWithPrivateMembers>(p_val_data);
            var p_data = (global::MyGame.Data.DataWithPrivateMembers?)p_val_data;
            
            _target.HandleData(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
