//HintName: __Descrio_System_Collections_Generic_List_MyGame_Data_DamageInfo___Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace System.Collections.Generic
{
    internal class __Descrio_System_Collections_Generic_List_MyGame_Data_DamageInfo__Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::System.Collections.Generic.List<global::MyGame.Data.DamageInfo>, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::System.Collections.Generic.List<global::MyGame.Data.DamageInfo>();
            if (dataDict.TryGetValue("Capacity", out var memberVal_Capacity) && memberVal_Capacity != null)
            {
                try
                {
                    instance.Capacity = (int)System.Convert.ChangeType(memberVal_Capacity, typeof(int));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Capacity' of type 'int'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("this[]", out var memberVal_this[]) && memberVal_this[] != null)
            {
                try
                {
                    if (TypeConverterRegistry.TryGetConverter(typeof(global::MyGame.Data.DamageInfo), out var converter_this[]))
                    {
                        instance.this[] = (global::MyGame.Data.DamageInfo?)converter_this[].Convert(memberVal_this[]);
                    }
                    else
                    {
                        throw new InvalidOperationException($"Converter not found for nested type 'global::MyGame.Data.DamageInfo'.");
                    }
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'this[]' of type 'global::MyGame.Data.DamageInfo'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
