//HintName: __Descrio_MyGame_Actions_ReturnValueActions_GetPower_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.ReturnValueActions.GetPower
    internal class __Descrio_MyGame_Actions_ReturnValueActions_GetPower_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.ReturnValueActions _target;
        public __Descrio_MyGame_Actions_ReturnValueActions_GetPower_Callable(global::MyGame.Actions.ReturnValueActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            var result = _target.GetPower();
            return new ValueTask<object?>(result);
        }
    }
}
#nullable disable
