//HintName: __Descrio_MyGame_Actions_MyActions_DoSomething_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.MyActions.DoSomething
    internal class __Descrio_MyGame_Actions_MyActions_DoSomething_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.MyActions _target;
        public __Descrio_MyGame_Actions_MyActions_DoSomething_Callable(global::MyGame.Actions.MyActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            p_val_data = global::Descrio.Core.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Actions.MyStruct>(p_val_data);
            if (p_val_data == null) throw new System.InvalidCastException($"Cannot convert null to non-nullable type global::MyGame.Actions.MyStruct for parameter 'data'.");
            var p_data = (global::MyGame.Actions.MyStruct)p_val_data!;
            
            _target.DoSomething(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
