//HintName: __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.InheritanceActions.ProcessDerivedData
    internal class __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.InheritanceActions _target;
        public __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable(global::MyGame.Actions.InheritanceActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            p_val_data = global::Descrio.Core.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.DerivedData>(p_val_data);
            var p_data = (global::MyGame.Data.DerivedData?)p_val_data;
            
            _target.ProcessDerivedData(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
