//HintName: __Descrio_MyGame_Data_Vector2D_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_Vector2D_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.Vector2D, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.Vector2D();
            if (dataDict.TryGetValue("X", out var memberVal_X) && memberVal_X != null)
            {
                try
                {
                    instance.X = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<float>(memberVal_X);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'X' of type 'float'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("Y", out var memberVal_Y) && memberVal_Y != null)
            {
                try
                {
                    instance.Y = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<float>(memberVal_Y);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Y' of type 'float'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
