//HintName: __DescrioGeneratedInitializers.g.cs
// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Descrio.Generated
{
    internal static class DescrioInitializer
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Actions.MyStruct), new global::MyGame.Actions.__Descrio_MyGame_Actions_MyStruct_Converter());
        }
    }
}
