//HintName: __Descrio_MyGame_Data_DamageInfo_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_DamageInfo_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.DamageInfo, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.DamageInfo();
            if (dataDict.TryGetValue("Amount", out var memberVal_Amount) && memberVal_Amount != null)
            {
                try
                {
                    instance.Amount = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<int>(memberVal_Amount);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Amount' of type 'int'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("IsCritical", out var memberVal_IsCritical) && memberVal_IsCritical != null)
            {
                try
                {
                    instance.IsCritical = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<bool>(memberVal_IsCritical);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'IsCritical' of type 'bool'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
