//HintName: __Descrio_MyGame_Actions_MyActions_ProcessList_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.MyActions.ProcessList
    internal class __Descrio_MyGame_Actions_MyActions_ProcessList_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.MyActions _target;
        public __Descrio_MyGame_Actions_MyActions_ProcessList_Callable(global::MyGame.Actions.MyActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            if (p_val_data is System.Collections.IEnumerable list_data)
            {
                p_val_data = list_data.Cast<object?>().Select(item =>
                {
                    if (item == null) throw new System.InvalidCastException($"Cannot convert null to non-nullable list item of type 'global::MyGame.Actions.MyStruct'.");
                    var itemTargetType = typeof(global::MyGame.Actions.MyStruct);
                    if (item != null && (item.GetType() == itemTargetType || itemTargetType.IsInstanceOfType(item))) return ({itemCastType})item;
                    if (Descrio.Execution.Converters.TypeConverterRegistry.TryGetConverter(itemTargetType, out var converter)) return ((global::MyGame.Actions.MyStruct))converter.Convert(item);
                    return ((global::MyGame.Actions.MyStruct))System.Convert.ChangeType(item, itemTargetType);
                }
                ).ToList();
            }
            var p_data = (global::System.Collections.Generic.List<global::MyGame.Actions.MyStruct>?)p_val_data;
            
            _target.ProcessList(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
