//HintName: __DescrioPublicAddCallablesExtensions.g.cs
// <auto-generated/>
using Descrio;

public static class __DescrioPublicAddCallablesExtensions
{
    public static ScriptRunner AddCallables(this ScriptRunner runner, global::MyGame.Actions.InheritanceActions target)
    {
        if (target == null) return runner;
        runner.AddCallable("ProcessDerivedData", new MyGame.Actions.__Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable(target));
        return runner;
    }
    
}
