//HintName: __Descrio_MyGame_Data_GenericData_string__Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_GenericData_string__Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.GenericData<string>, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.GenericData<string>();
            if (dataDict.TryGetValue("Value", out var memberVal_Value) && memberVal_Value != null)
            {
                try
                {
                    instance.Value = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<string>(memberVal_Value);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'Value' of type 'string'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
