//HintName: __Descrio_MyGame_Actions_MyActions_ProcessArray_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.MyActions.ProcessArray
    internal class __Descrio_MyGame_Actions_MyActions_ProcessArray_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.MyActions _target;
        public __Descrio_MyGame_Actions_MyActions_ProcessArray_Callable(global::MyGame.Actions.MyActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            if (p_val_data is System.Collections.IEnumerable list_data)
            {
                p_val_data = list_data.Cast<object?>().Select(item => global::Descrio.Core.Execution.Converters.RuntimeConversionHelper.ConvertItem<int>(item)).ToArray();
            }
            var p_data = (int[]?)p_val_data;
            
            _target.ProcessArray(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
