//HintName: __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.CharacterActions.ExecuteSkill
    internal class __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.CharacterActions _target;
        public __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable(global::MyGame.Actions.CharacterActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_skill;
            if (!args.TryGetValue("skill", out p_val_skill)) throw new System.ArgumentException("Missing required argument: 'skill'.");
            p_val_skill = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.SkillData>(p_val_skill);
            var p_skill = (global::MyGame.Data.SkillData?)p_val_skill;
            
            _target.ExecuteSkill(p_skill);
            return default;
        }
    }
}
#nullable disable
