//HintName: __Descrio_MyGame_Data_DerivedData_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_DerivedData_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.DerivedData, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.DerivedData();
            if (dataDict.TryGetValue("DerivedProp", out var memberVal_DerivedProp) && memberVal_DerivedProp != null)
            {
                try
                {
                    instance.DerivedProp = (string?)System.Convert.ChangeType(memberVal_DerivedProp, typeof(string));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'DerivedProp' of type 'string'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("BaseProp", out var memberVal_BaseProp) && memberVal_BaseProp != null)
            {
                try
                {
                    instance.BaseProp = (string?)System.Convert.ChangeType(memberVal_BaseProp, typeof(string));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'BaseProp' of type 'string'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
