//HintName: __DescrioGeneratedInitializers.g.cs
// <auto-generated/>
using Descrio.Execution.Converters;

namespace Descrio.Generated
{
    internal static partial class DescrioInitializer
    {
        internal static void Initialize()
        {
            TypeConverterRegistry.RegisterCore(typeof(global::MyGame.Data.EffectData), new MyGame.Data.__Descrio_MyGame_Data_EffectData_Converter());
        }
    }
}

namespace Descrio.Execution.Converters
{
    public static partial class TypeConverterRegistry
    {
        static partial void InitializeConverters()
        {
            Descrio.Generated.DescrioInitializer.Initialize();
        }
    }
}
