//HintName: __DescrioPublicAddCallablesExtensions.g.cs
// <auto-generated/>
using Descrio;

public static class __DescrioPublicAddCallablesExtensions
{
    public static ScriptRunner AddCallables(this ScriptRunner runner, global::MyGame.Actions.ReturnValueActions target)
    {
        if (target == null) return runner;
        runner.AddCallable("GetPower", new MyGame.Actions.__Descrio_MyGame_Actions_ReturnValueActions_GetPower_Callable(target));
        runner.AddCallable("GetDefaultEffect", new MyGame.Actions.__Descrio_MyGame_Actions_ReturnValueActions_GetDefaultEffect_Callable(target));
        return runner;
    }
    
}
