//HintName: __DescrioPublicAddCallablesExtensions.g.cs
// <auto-generated/>
using Descrio;

public static class __DescrioPublicAddCallablesExtensions
{
    public static ScriptRunner AddCallables(this ScriptRunner runner, global::MyGame.Actions.SomeActions target)
    {
        if (target == null) return runner;
        runner.AddCallable("HandleData", new MyGame.Actions.__Descrio_MyGame_Actions_SomeActions_HandleData_Callable(target));
        return runner;
    }
    
}
