//HintName: __Descrio_MyGame_Actions_BadActions_Process_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.BadActions.Process
    internal class __Descrio_MyGame_Actions_BadActions_Process_Callable : global::Descrio.Abstractions.ICallable
    {
        private readonly global::MyGame.Actions.BadActions _target;
        public __Descrio_MyGame_Actions_BadActions_Process_Callable(global::MyGame.Actions.BadActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            p_val_data = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<global::MyGame.Data.InvalidData>(p_val_data);
            var p_data = (global::MyGame.Data.InvalidData?)p_val_data;
            
            _target.Process(p_data);
            return default;
        }
    }
}
#nullable disable
