//HintName: __Descrio_MyGame_Actions_DuplicateActions_ActionOne_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.DuplicateActions.ActionOne
    internal class __Descrio_MyGame_Actions_DuplicateActions_ActionOne_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.DuplicateActions _target;
        public __Descrio_MyGame_Actions_DuplicateActions_ActionOne_Callable(global::MyGame.Actions.DuplicateActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            _target.ActionOne();
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
