//HintName: __Descrio_MyGame_Data_DataWithPrivateMembers_Converter.g.cs
// <auto-generated/>
#nullable enable
using Descrio.Execution.Converters;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyGame.Data
{
    internal class __Descrio_MyGame_Data_DataWithPrivateMembers_Converter : ITypeConverter
    {
        public object? Convert(object? source)
        {
            if (source == null) return null;
            if (!(source is IDictionary<object, object> dataDict))
            {
                throw new InvalidCastException($"Expected a dictionary to map to global::MyGame.Data.DataWithPrivateMembers, but received a {source.GetType().Name}.");
            }
            
            var instance = new global::MyGame.Data.DataWithPrivateMembers();
            if (dataDict.TryGetValue("PublicData", out var memberVal_PublicData) && memberVal_PublicData != null)
            {
                try
                {
                    instance.PublicData = (string?)System.Convert.ChangeType(memberVal_PublicData, typeof(string));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'PublicData' of type 'string'. See inner exception for details.", ex);
                }
            }
            if (dataDict.TryGetValue("PropertyWithPrivateSetter", out var memberVal_PropertyWithPrivateSetter) && memberVal_PropertyWithPrivateSetter != null)
            {
                try
                {
                    instance.PropertyWithPrivateSetter = (int)System.Convert.ChangeType(memberVal_PropertyWithPrivateSetter, typeof(int));
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to map member 'PropertyWithPrivateSetter' of type 'int'. See inner exception for details.", ex);
                }
            }
            return instance;
        }
    }
}
#nullable disable
