//HintName: __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.CharacterActions.ExecuteSkill
    internal class __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.CharacterActions _target;
        public __Descrio_MyGame_Actions_CharacterActions_ExecuteSkill_Callable(global::MyGame.Actions.CharacterActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_skill;
            if (!args.TryGetValue("skill", out p_val_skill)) throw new System.ArgumentException("Missing required argument: 'skill'.");
            var p_targetType_skill = typeof(global::MyGame.Data.SkillData);
            if (p_val_skill != null && !p_targetType_skill.IsInstanceOfType(p_val_skill))
            {
                if (Descrio.Execution.Converters.TypeConverterRegistry.TryGetConverter(p_targetType_skill, out var converter_skill))
                {
                    p_val_skill = converter_skill.Convert(p_val_skill);
                }
                else
                {
                    p_val_skill = System.Convert.ChangeType(p_val_skill, p_targetType_skill);
                }
            }
            var p_skill = (global::MyGame.Data.SkillData?)p_val_skill;
            
            _target.ExecuteSkill(p_skill);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
