//HintName: __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading.Tasks;

namespace MyGame.Actions
{
    // Auto-generated wrapper for global::MyGame.Actions.InheritanceActions.ProcessDerivedData
    internal class __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable : Descrio.ICallable
    {
        private readonly global::MyGame.Actions.InheritanceActions _target;
        public __Descrio_MyGame_Actions_InheritanceActions_ProcessDerivedData_Callable(global::MyGame.Actions.InheritanceActions target) => _target = target;
        
        public System.Threading.Tasks.ValueTask<object?> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)
        {
            object? p_val_data;
            if (!args.TryGetValue("data", out p_val_data)) throw new System.ArgumentException("Missing required argument: 'data'.");
            var p_targetType_data = typeof(global::MyGame.Data.DerivedData);
            if (p_val_data != null && !p_targetType_data.IsInstanceOfType(p_val_data))
            {
                if (Descrio.Execution.Converters.TypeConverterRegistry.TryGetConverter(p_targetType_data, out var converter_data))
                {
                    p_val_data = converter_data.Convert(p_val_data);
                }
                else
                {
                    p_val_data = System.Convert.ChangeType(p_val_data, p_targetType_data);
                }
            }
            var p_data = (global::MyGame.Data.DerivedData?)p_val_data;
            
            _target.ProcessDerivedData(p_data);
            return new ValueTask<object?>(null);
        }
    }
}
#nullable disable
