//HintName: __DescrioGeneratedInitializers.g.cs
// <auto-generated/>
using System.Runtime.CompilerServices;

namespace Descrio.Generated
{
    internal static class DescrioInitializer
    {
        [ModuleInitializer]
        internal static void Initialize()
        {
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Data.CharacterStats), new global::MyGame.Data.__Descrio_MyGame_Data_CharacterStats_Converter());
            global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof(global::MyGame.Data.EffectData), new global::MyGame.Data.__Descrio_MyGame_Data_EffectData_Converter());
        }
    }
}
