using Descrio.Generator.Callable.Models;
using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class CallableWrapperEmitter
    {
        public static string BuildWrapperClass(CallableClassInfo classInfo, CallableMethodInfo methodInfo)
        {
            var sb = new IndentedStringBuilder();
            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();

            var hasNamespace = !string.IsNullOrEmpty(classInfo.Namespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                sb.AppendLine("{");
                sb.IncreaseIndent();
            }

            sb.AppendLine($"// Auto-generated wrapper for {classInfo.FullClassName}.{methodInfo.MethodName}");
            sb.AppendLine($"internal class {wrapperClassName} : global::Descrio.Abstractions.ICallable");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"private readonly {classInfo.FullClassName} _target;");
                sb.AppendLine($"public {wrapperClassName}({classInfo.FullClassName} target) => _target = target;");
                sb.AppendLine();

                var asyncKeyword = methodInfo.IsAwaitable ? "async " : "";
                sb.AppendLine($"public {asyncKeyword}System.Threading.Tasks.ValueTask<object?> CallAsync(global::Descrio.Data.Arguments args, global::Descrio.Execution.ExecutionContext context)");
                using (sb.IndentedBlock())
                {
                    var callParams = AppendParametersLogic(sb, methodInfo.Parameters);
                    AppendMethodCallLogic(sb, methodInfo, callParams);
                }
            }

            if (hasNamespace)
            {
                sb.DecreaseIndent();
                sb.AppendLine("}");
            }
            sb.AppendLine("#nullable disable");

            return sb.ToString();
        }

        private static List<string> AppendParametersLogic(IndentedStringBuilder sb, List<ParameterInfo> parameters)
        {
            var callParamNames = new List<string>();
            foreach (var param in parameters)
            {
                var typeName = param.TypeName;
                if (typeName == "global::System.Threading.CancellationToken")
                {
                    callParamNames.Add("context.CancellationToken");
                    continue;
                }
                if (typeName == "global::Descrio.Execution.ExecutionContext")
                {
                    callParamNames.Add("context");
                    continue;
                }

                var paramName = param.Name;

                sb.AppendLine($"object? p_val_{paramName};");
                if (param.HasDefaultValue)
                {
                    sb.AppendLine($"p_val_{paramName} = args.TryGetValue(\"{paramName}\", out var val_{paramName}) ? val_{paramName} : {CodeGenerationHelpers.GetParameterDefaultValueLiteral(param)};");
                }
                else
                {
                    sb.AppendLine($"if (!args.TryGetValue(\"{paramName}\", out p_val_{paramName})) throw new System.ArgumentException(\"Missing required argument: '{paramName}'.\");");
                }

                var isList = Descrio.Generator.Utils.CodeGenerationHelpers.IsGenericList(param.Type, out var listItemType);
                var isArray = Descrio.Generator.Utils.CodeGenerationHelpers.IsArray(param.Type, out var arrayItemType);

                if (isList || isArray)
                {
                    var itemType = listItemType ?? arrayItemType;
                    var itemTypeName = itemType.ToFullTypeName();
                    var linqMethod = isList ? "ToList" : "ToArray";

                    sb.AppendLine($"if (p_val_{paramName} is System.Collections.IEnumerable list_{paramName})");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"p_val_{paramName} = list_{paramName}.Cast<object?>().Select(item => " +
                                      $"global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{itemTypeName}>(item)" +
                                      $").{linqMethod}();");
                    }
                }
                else
                {
                    sb.AppendLine($"p_val_{paramName} = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{typeName}>(p_val_{paramName});");
                }

                if (param.Type.IsValueType && param.Type.NullableAnnotation != Microsoft.CodeAnalysis.NullableAnnotation.Annotated)
                {
                    sb.AppendLine($"if (p_val_{paramName} == null) throw new System.InvalidCastException($\"Cannot convert null to non-nullable type {param.Type.ToDisplayString(Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat)} for parameter '{paramName}'.\");");
                }

                var castExpression = CodeGenerationHelpers.GetCastExpression(param.Type, $"p_val_{paramName}");
                sb.AppendLine($"var p_{paramName} = {castExpression};");

                callParamNames.Add($"p_{paramName}");
                sb.AppendLine();
            }
            return callParamNames;
        }

        private static void AppendMethodCallLogic(IndentedStringBuilder sb, CallableMethodInfo methodInfo, List<string> callParamNames)
        {
            var callParamsStr = string.Join(", ", callParamNames);

            if (methodInfo.IsAwaitable)
            {
                if (methodInfo.ReturnsValue)
                {
                    sb.AppendLine($"var result = await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return (object?)result;");
                }
                else
                {
                    sb.AppendLine($"await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return null;");
                }
            }
            else
            {
                if (methodInfo.ReturnsValue)
                {
                    sb.AppendLine($"var result = _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return new ValueTask<object?>(result);");
                }
                else
                {
                    sb.AppendLine($"_target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return new ValueTask<object?>(null);");
                }
            }
        }
    }
}