using Descrio.Generator.Callable.Models;
using Descrio.Generator.Utils;
using System.Collections.Generic;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class ExtensionMethodEmitter
    {
        public static string BuildRegistrationClass(string accessibility, string className, IEnumerable<CallableClassInfo> classInfos)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Descrio;");
            sb.AppendLine();
            sb.AppendLine($"{accessibility} static class {className}");
            using (sb.IndentedBlock())
            {
                foreach (var classInfo in classInfos)
                {
                    sb.AppendLine($"public static ScriptRunner AddCallables(this ScriptRunner runner, {classInfo.FullClassName} target)");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine("if (target == null) return runner;");

                        foreach (var methodInfo in classInfo.Methods)
                        {
                            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";
                            var fullWrapperName = string.IsNullOrEmpty(classInfo.Namespace) ? wrapperClassName : $"{classInfo.Namespace}.{wrapperClassName}";
                            sb.AppendLine($"runner.AddCallable(\"{methodInfo.CallableName}\", new {fullWrapperName}(target));");
                        }

                        sb.AppendLine("return runner;");
                    }
                    sb.AppendLine();
                }
            }
            return sb.ToString();
        }
    }
}