using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class InitializerEmitter
    {
        public static string BuildInitializerClass(IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();

            sb.AppendLine("namespace Descrio.Generated");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("internal static class DescrioInitializer");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("[ModuleInitializer]");
                    sb.AppendLine("internal static void Initialize()");
                    using (sb.IndentedBlock())
                    {
                        foreach (var typeSymbol in allMappableTypes)
                        {
                            var fullTypeName = typeSymbol.ToFullTypeName();
                            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace("?", "_");
                            var converterClassName = $"__Descrio_{safeClassName}_Converter";

                            var ns = typeSymbol.ContainingNamespace;
                            var hasNamespace = ns != null && !ns.IsGlobalNamespace;
                            var fullConverterClassName = hasNamespace
                                ? $"global::{ns.ToDisplayString()}.{converterClassName}"
                                : $"global::{converterClassName}";

                            sb.AppendLine($"global::Descrio.Execution.Converters.TypeConverterRegistry.Register(typeof({fullTypeName}), new {fullConverterClassName}());");
                        }
                    }
                }
            }
            return sb.ToString();
        }
    }
}