using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class InitializerEmitter
    {
        public static string BuildInitializerClass(IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Descrio.Execution.Converters;");
            sb.AppendLine();

            sb.AppendLine("namespace Descrio.Generated");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("internal static partial class DescrioInitializer");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("internal static void Initialize()");
                    using (sb.IndentedBlock())
                    {
                        foreach (var typeSymbol in allMappableTypes)
                        {
                            var fullTypeName = typeSymbol.ToFullTypeName();
                            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace("?", "_");
                            var converterClassName = $"__Descrio_{safeClassName}_Converter";

                            var ns = typeSymbol.ContainingNamespace;
                            var hasNamespace = ns != null && !ns.IsGlobalNamespace;
                            var fullConverterClassName = hasNamespace
                                ? $"{ns.ToDisplayString()}.{converterClassName}"
                                : converterClassName;

                            sb.AppendLine($"TypeConverterRegistry.RegisterCore(typeof({fullTypeName}), new {fullConverterClassName}());");
                        }
                    }
                }
            }

            sb.AppendLine();
            sb.AppendLine("namespace Descrio.Execution.Converters");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("public static partial class TypeConverterRegistry");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("static partial void InitializeConverters()");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine("Descrio.Generated.DescrioInitializer.Initialize();");
                    }
                }
            }

            return sb.ToString();
        }
    }
}