using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class TypeConverterEmitter
    {
        public static string BuildTypeConverterClass(ITypeSymbol typeSymbol, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var fullTypeName = typeSymbol.ToFullTypeName();
            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace("?", "_");
            var converterClassName = $"__Descrio_{safeClassName}_Converter";

            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Descrio.Execution.Converters;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            var ns = typeSymbol.ContainingNamespace;
            var hasNamespace = ns != null && !ns.IsGlobalNamespace;

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns.ToDisplayString()}");
                sb.AppendLine("{");
                sb.IncreaseIndent();
            }

            sb.AppendLine($"internal class {converterClassName} : ITypeConverter");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"public object? Convert(object? source)");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("if (source == null) return null;");
                    sb.AppendLine("if (!(source is IDictionary<object, object> dataDict))");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"throw new InvalidCastException($\"Expected a dictionary to map to {fullTypeName}, but received a {{source.GetType().Name}}.\");");
                    }
                    sb.AppendLine();
                    sb.AppendLine($"var instance = new {fullTypeName}();");

                    foreach (var member in SymbolAnalyzer.GetAllMappableMembers(typeSymbol))
                    {
                        (string? memberName, ITypeSymbol? memberType, bool canWrite) = SymbolAnalyzer.GetMemberInfo(member);
                        if (!canWrite || memberName is null || memberType is null)
                            continue;

                        sb.AppendLine($"if (dataDict.TryGetValue(\"{memberName}\", out var memberVal_{memberName}) && memberVal_{memberName} != null)");
                        using (sb.IndentedBlock())
                        {
                            sb.AppendLine("try");
                            using (sb.IndentedBlock())
                            {
                                AppendMemberConversionLogic(sb, "instance", memberName, memberType, allMappableTypes);
                            }
                            sb.AppendLine("catch (Exception ex)");
                            using (sb.IndentedBlock())
                            {
                                var memberTypeName = memberType.ToFullTypeName();
                                sb.AppendLine($"throw new InvalidOperationException(\"Failed to map member '{memberName}' of type '{memberTypeName}'. See inner exception for details.\", ex);");
                            }
                        }
                    }
                    sb.AppendLine("return instance;");
                }
            }

            if (hasNamespace)
            {
                sb.DecreaseIndent();
                sb.AppendLine("}");
            }
            sb.AppendLine("#nullable disable");

            return sb.ToString();
        }

        private static void AppendMemberConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol memberType, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var valueToConvert = $"memberVal_{memberName}";
            var memberTypeName = memberType.ToFullTypeName();

            if (CodeGenerationHelpers.IsGenericList(memberType, out var listElementType))
            {
                AppendCollectionConversionLogic(sb, instanceName, memberName, listElementType!, valueToConvert, "ToList", allMappableTypes);
                return;
            }

            if (CodeGenerationHelpers.IsArray(memberType, out var arrayElementType))
            {
                AppendCollectionConversionLogic(sb, instanceName, memberName, arrayElementType!, valueToConvert, "ToArray", allMappableTypes);
                return;
            }

            if (CodeGenerationHelpers.IsGenericDictionary(memberType, out var keyType, out var valueType))
            {
                AppendDictionaryConversionLogic(sb, instanceName, memberName, keyType!, valueType!, valueToConvert, allMappableTypes);
                return;
            }
            
            sb.AppendLine($"instance.{memberName} = global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{memberTypeName}>({valueToConvert});");
        }

        private static void AppendDictionaryConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol keyType, ITypeSymbol valueType, string valueToConvert, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var keyTypeName = keyType.ToFullTypeName();
            var valueTypeName = valueType.ToFullTypeName();

            sb.AppendLine($"if ({valueToConvert} is not System.Collections.IDictionary dict_{memberName}) throw new InvalidCastException($\"Expected a dictionary for member '{memberName}'.\");");
            sb.AppendLine();
            sb.AppendLine($"{instanceName}.{memberName} = dict_{memberName}");
            using (sb.Indent())
            {
                sb.AppendLine($".Cast<System.Collections.DictionaryEntry>()");
                sb.AppendLine($".ToDictionary(");
                using (sb.Indent())
                {
                    sb.AppendLine($"entry => global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{keyTypeName}>(entry.Key) ?? throw new System.InvalidCastException($\"Dictionary key for member '{memberName}' cannot be null.\"),");

                    var valueConversion = $"global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{valueTypeName}>(entry.Value)";
                    if (valueType.IsReferenceType && valueType.NullableAnnotation == NullableAnnotation.NotAnnotated)
                    {
                        valueConversion += $" ?? throw new System.InvalidCastException($\"Dictionary value for member '{memberName}' cannot be null.\")";
                    }
                    sb.AppendLine($"entry => {valueConversion});");
                }
            }
        }

        private static void AppendCollectionConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol itemType, string valueToConvert, string linqMethod, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var itemTypeName = itemType.ToFullTypeName();
            var itemCastType = CodeGenerationHelpers.GetCastTargetString(itemType);

            sb.AppendLine($"if ({valueToConvert} is not System.Collections.IEnumerable list_{memberName}) throw new InvalidCastException(\"Expected a list or array.\");");
            sb.AppendLine();
            sb.AppendLine($"{instanceName}.{memberName} = list_{memberName}.Cast<object?>().Select(item =>");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"return global::Descrio.Execution.Converters.RuntimeConversionHelper.ConvertItem<{itemTypeName}>(item);");
            }
            sb.AppendLine($").{linqMethod}();");
        }
    }
}