using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Descrio.Generator.Callable.Emitter
{
    internal static class TypeConverterEmitter
    {
        public static string BuildTypeConverterClass(ITypeSymbol typeSymbol, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var fullTypeName = typeSymbol.ToFullTypeName();
            var safeClassName = fullTypeName.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_");
            var converterClassName = $"__Descrio_{safeClassName}_Converter";

            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Descrio.Execution.Converters;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            var ns = typeSymbol.ContainingNamespace;
            var hasNamespace = ns != null && !ns.IsGlobalNamespace;

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {ns.ToDisplayString()}");
                sb.AppendLine("{");
                sb.IncreaseIndent();
            }

            sb.AppendLine($"internal class {converterClassName} : ITypeConverter");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"public object? Convert(object? source)");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine("if (source == null) return null;");
                    sb.AppendLine("if (!(source is IDictionary<object, object> dataDict))");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine($"throw new InvalidCastException($\"Expected a dictionary to map to {fullTypeName}, but received a {{source.GetType().Name}}.\");");
                    }
                    sb.AppendLine();
                    sb.AppendLine($"var instance = new {fullTypeName}();");

                    foreach (var member in typeSymbol.GetMembers().OfType<ISymbol>().Where(m => m is IPropertySymbol || m is IFieldSymbol))
                    {
                        (string? memberName, ITypeSymbol? memberType, bool canWrite) = SymbolAnalyzer.GetMemberInfo(member);
                        if (!canWrite || memberName is null || memberType is null)
                            continue;

                        sb.AppendLine($"if (dataDict.TryGetValue(\"{memberName}\", out var memberVal_{memberName}) && memberVal_{memberName} != null)");
                        using (sb.IndentedBlock())
                        {
                            sb.AppendLine("try");
                            using (sb.IndentedBlock())
                            {
                                AppendMemberConversionLogic(sb, "instance", memberName, memberType, allMappableTypes);
                            }
                            sb.AppendLine("catch (Exception ex)");
                            using (sb.IndentedBlock())
                            {
                                var memberTypeName = memberType.ToFullTypeName();
                                sb.AppendLine($"throw new InvalidOperationException(\"Failed to map member '{memberName}' of type '{memberTypeName}'. See inner exception for details.\", ex);");
                            }
                        }
                    }
                    sb.AppendLine("return instance;");
                }
            }

            if (hasNamespace)
            {
                sb.DecreaseIndent();
                sb.AppendLine("}");
            }
            sb.AppendLine("#nullable disable");

            return sb.ToString();
        }

        private static void AppendMemberConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol memberType, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var valueToConvert = $"memberVal_{memberName}";
            var memberTypeName = memberType.ToFullTypeName();
            var castType = CodeGenerationHelpers.GetCastTargetString(memberType);

            if (memberType.TypeKind == TypeKind.Enum)
            {
                sb.AppendLine($"if ({valueToConvert} is string strVal_{memberName})");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName})Enum.Parse(typeof({memberTypeName}), strVal_{memberName}, true);");
                }
                sb.AppendLine("else");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = ({memberTypeName})Enum.ToObject(typeof({memberTypeName}), {valueToConvert});");
                }
                return;
            }

            if (CodeGenerationHelpers.IsGenericList(memberType, out var listElementType))
            {
                AppendCollectionConversionLogic(sb, instanceName, memberName, listElementType!, valueToConvert, "ToList", allMappableTypes);
                return;
            }

            if (CodeGenerationHelpers.IsArray(memberType, out var arrayElementType))
            {
                AppendCollectionConversionLogic(sb, instanceName, memberName, arrayElementType!, valueToConvert, "ToArray", allMappableTypes);
                return;
            }

            if (allMappableTypes.Contains(memberType, SymbolEqualityComparer.Default))
            {
                sb.AppendLine($"if (TypeConverterRegistry.TryGetConverter(typeof({memberTypeName}), out var converter_{memberName}))");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"{instanceName}.{memberName} = {castType}converter_{memberName}.Convert({valueToConvert});");
                }
                sb.AppendLine("else");
                using (sb.IndentedBlock())
                {
                    sb.AppendLine($"throw new InvalidOperationException($\"Converter not found for nested type '{memberTypeName}'.\");");
                }
                return;
            }

            sb.AppendLine($"{instanceName}.{memberName} = {castType}System.Convert.ChangeType({valueToConvert}, typeof({memberTypeName}));");
        }

        private static void AppendCollectionConversionLogic(IndentedStringBuilder sb, string instanceName, string memberName, ITypeSymbol itemType, string valueToConvert, string linqMethod, IReadOnlyCollection<ITypeSymbol> allMappableTypes)
        {
            var itemTypeName = itemType.ToFullTypeName();
            var itemCastType = CodeGenerationHelpers.GetCastTargetString(itemType);

            sb.AppendLine($"if ({valueToConvert} is not System.Collections.IEnumerable list_{memberName}) throw new InvalidCastException(\"Expected a list or array.\");");
            sb.AppendLine();
            sb.AppendLine($"{instanceName}.{memberName} = list_{memberName}.Cast<object?>().Select(item =>");
            using (sb.IndentedBlock())
            {
                sb.AppendLine("if (item == null) return default;");
                if (allMappableTypes.Contains(itemType, SymbolEqualityComparer.Default))
                {
                    sb.AppendLine($"if (!TypeConverterRegistry.TryGetConverter(typeof({itemTypeName}), out var converter)) throw new InvalidOperationException($\"Converter for list item '{itemTypeName}' not found.\");");
                    sb.AppendLine($"return {itemCastType}converter.Convert(item);");
                }
                else
                {
                    sb.AppendLine($"return {itemCastType}System.Convert.ChangeType(item, typeof({itemTypeName}));");
                }
            }
            sb.AppendLine($").{linqMethod}();");
        }
    }
}