using Descrio.Generator.Callable.Models;
using Descrio.Generator.Utils;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace Descrio.Generator.Callable
{
    internal static class CodeBuilder
    {
        public static string BuildWrapperClass(CallableClassInfo classInfo, CallableMethodInfo methodInfo)
        {
            var sb = new IndentedStringBuilder();
            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(classInfo.Namespace))
            {
                sb.AppendLine($"namespace {classInfo.Namespace}");
                using (sb.IndentedBlock())
                {
                    AppendClassContent(sb, classInfo, methodInfo, wrapperClassName);
                }
            }
            else
            {
                AppendClassContent(sb, classInfo, methodInfo, wrapperClassName);
            }

            return sb.ToString();
        }

        private static void AppendClassContent(IndentedStringBuilder sb, CallableClassInfo classInfo, CallableMethodInfo methodInfo, string wrapperClassName)
        {
            sb.AppendLine($"// Auto-generated wrapper for {classInfo.FullClassName}.{methodInfo.MethodName}");
            sb.AppendLine($"internal class {wrapperClassName} : Descrio.ICallable");
            using (sb.IndentedBlock())
            {
                sb.AppendLine($"private readonly {classInfo.FullClassName} _target;");
                sb.AppendLine($"public {wrapperClassName}({classInfo.FullClassName} target) => _target = target;");
                sb.AppendLine();
                sb.AppendLine("public async System.Threading.Tasks.ValueTask<object> CallAsync(Descrio.Arguments args, Descrio.Execution.ExecutionContext context)");
                using (sb.IndentedBlock())
                {
                    var callParams = AppendParametersLogic(sb, methodInfo.Parameters);
                    AppendMethodCallLogic(sb, methodInfo, callParams);
                }
            }
        }

        private static List<string> AppendParametersLogic(IndentedStringBuilder sb, List<ParameterInfo> parameters)
        {
            var callParamNames = new List<string>();
            foreach (var param in parameters)
            {
                var typeName = param.TypeName;
                if (typeName == "global::System.Threading.CancellationToken")
                {
                    callParamNames.Add("context.CancellationToken");
                    continue;
                }
                if (typeName == "global::Descrio.Execution.ExecutionContext")
                {
                    callParamNames.Add("context");
                    continue;
                }

                var paramName = param.Name;
                sb.AppendLine($"object p_val_{paramName};");
                if (param.HasDefaultValue)
                {
                    sb.AppendLine($"p_val_{paramName} = args.TryGetValue(\"{paramName}\", out var val_{paramName}) ? val_{paramName} : {param.DefaultValueAsString};");
                }
                else
                {
                    sb.AppendLine($"args.TryGetValue(\"{paramName}\", out p_val_{paramName});");
                }

                if (param.Type.TypeKind == TypeKind.Interface || param.Type.SpecialType == SpecialType.System_Object)
                {
                    sb.AppendLine($"var p_{paramName} = ({typeName})p_val_{paramName};");
                }
                else
                {
                    sb.AppendLine($"var p_{paramName} = p_val_{paramName} == null ? default({typeName}) : ({typeName})Convert.ChangeType(p_val_{paramName}, typeof({typeName}));");
                }
                callParamNames.Add($"p_{paramName}");
                sb.AppendLine(); // Add a blank line for readability
            }
            return callParamNames;
        }

        private static void AppendMethodCallLogic(IndentedStringBuilder sb, CallableMethodInfo methodInfo, List<string> callParamNames)
        {
            var callParamsStr = string.Join(", ", callParamNames);
            var returnType = methodInfo.ReturnType;

            if (returnType.SpecialType == SpecialType.System_Void)
            {
                sb.AppendLine($"_target.{methodInfo.MethodName}({callParamsStr});");
                sb.AppendLine("return await new ValueTask<object>((object)null);");
            }
            else
            {
                if (returnType is INamedTypeSymbol namedType && namedType.IsGenericType && (namedType.ConstructedFrom.ToDisplayString().Contains("Task") || namedType.ConstructedFrom.ToDisplayString().Contains("ValueTask")))
                {
                    sb.AppendLine($"var result = await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return (object)result;");
                }
                else if (returnType.ToDisplayString().Contains("Task"))
                {
                    sb.AppendLine($"await _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return await new ValueTask<object>((object)null);");
                }
                else
                {
                    sb.AppendLine($"var result = _target.{methodInfo.MethodName}({callParamsStr});");
                    sb.AppendLine("return await new ValueTask<object>(result);");
                }
            }
        }

        public static string BuildRegistrationClass(IEnumerable<CallableClassInfo> classInfos)
        {
            var sb = new IndentedStringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Descrio;");
            sb.AppendLine();
            sb.AppendLine("public static class __DescrioAddCallablesExtensions");
            using (sb.IndentedBlock())
            {
                foreach (var classInfo in classInfos)
                {
                    sb.AppendLine($"public static ScriptRunner AddCallables(this ScriptRunner runner, {classInfo.FullClassName} target)");
                    using (sb.IndentedBlock())
                    {
                        sb.AppendLine("if (target == null) return runner;");

                        foreach (var methodInfo in classInfo.Methods)
                        {
                            var wrapperClassName = $"__Descrio_{classInfo.SafeFileName}_{methodInfo.MethodName}_Callable";
                            var fullWrapperName = string.IsNullOrEmpty(classInfo.Namespace) ? wrapperClassName : $"{classInfo.Namespace}.{wrapperClassName}";
                            sb.AppendLine($"runner.AddCallable(\"{methodInfo.CallableName}\", new {fullWrapperName}(target));");
                        }

                        sb.AppendLine("return runner;");
                    }
                    sb.AppendLine(); // Add a blank line between methods
                }
            }
            return sb.ToString();
        }
    }
}